baseURL: 'https://www.dfioravanti.com/'
languageCode: en-us
title: Diego Fioravanti
theme: hugo-PaperMod
canonifyURLs: true
copyright: Diego Fioravanti
enableRobotsTXT: false

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: Archive
          url: archive/
          weight: 5
        - name: About
          url: about/
          weight: 6
        - name: Tags
          url: tags/
          weight: 7
        - name: Impressum
          url: impressum/


# Disable everything so no cookie is needed
privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: true
